services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: asistencias_db
      MYSQL_USER: asistencias_user
      MYSQL_PASSWORD: asistencias_pass
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: >
      mysqld
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://asistencias_user:asistencias_pass@db:3306/asistencias_db?charset=utf8mb4"
      PYTHONPATH: "/app"
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - .:/app
    command: uvicorn app.web.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
